### ISSUE TITLE
Not able to connect Dobot 

### ISSUE THREAD

**Issue by VijayAnand-Kandaswamy** [jkaniuka/magician_ros2#7]
After following the command when I connect I am getting error , " Dobot is disconnected and check if USB cable and power adapter are plugged in"

I request you to help to solve the above erroe

**Comment by jkaniuka** [comment]
Hi @VijayAnand-Kandaswamy, 
please connect Dobot Magician to computer via USB, power it up and then execute `lsusb` command in terminal. You should see a device named **Silicon Labs CP210x UART Bridge**.  Which operating system are you using btw?

**Comment by VijayAnand-Kandaswamy** [comment]
Thank you for your reply 
When i gave lsusb , I didn't get Silicon Labs CP210x UART Bridge
I am using Ubuntu 22.0.4 LTS .
Please see the screenshot for more info..
![Screenshot from 2024-03-02 11-13-47](https://github.com/jkaniuka/magician_ros2/assets/108893460/b7566d73-0d5f-4da6-ae4a-c52c3ce9326e)
![Screenshot from 2024-03-02 11-13-36](https://github.com/jkaniuka/magician_ros2/assets/108893460/ec39045b-655f-4cf8-944a-75936f4bd819)

**Comment by VijayAnand-Kandaswamy** [comment]
I followed all the step and I connected the DOBOT with USB and power on, but still its not working , Please let me know what is the mistake ...

**Comment by VijayAnand-Kandaswamy** [comment]
I think instead of Silicon Labs CP210x UART Bridge. I am getting  Qinheng Electronics USB single Serial ....as the port connected for DOBOT. Please check the screenshot ....

**Comment by jkaniuka** [comment]
Hi @VijayAnand-Kandaswamy, 
I thoroughly investigated your issue and came across the following forums on the internet:

- [[SOLVED] Connection between Dobot Magician and Linux](https://forum.dobot.cc/t/solved-connection-between-dobot-magician-and-linux/244) - July 2017
- [Dobot and Robot Operating System](https://hotblackrobotics.github.io/en/blog/2018/06/29/ros-dobot/) - June 2018

Both of them mention the QinHeng Electronics chip. Maybe these chips were mounted in older Dobot models?
I've added a patch (https://github.com/jkaniuka/magician_ros2/commit/3b903ef0bf2db9dc2e1dcf16001dab02e8d36e0c) that should allow you to launch the control system. Let me know if this resolves your problem :wink:

**Comment by hemachandiran14** [comment]
hi @jkaniuka , I'm an associate of @VijayAnand-Kandaswamy
When we tried to communicate with the dobot using cutecom, dobot went into the homing position.
But while using your fix, nothing happened ,same error persists.

**Comment by hemachandiran14** [comment]
hi @jkaniuka , I'm an associate of @VijayAnand-Kandaswamy
Thanks for the solution, now the serial communication is happening but we couldn't install the pyKDL module
![Screenshot from 2024-03-05 14-40-43](https://github.com/jkaniuka/magician_ros2/assets/119487036/72a2dca5-35b9-40df-8e79-4d7b5ffda5ab)

**Comment by jkaniuka** [comment]
Hi @hemachandiran14,
I will verify it tomorrow, but as for now I think that you can ignore installing PyKDL from _requirements.txt_ and just install it using `sudo apt install python3-pykdl` :wink:

**Comment by jkaniuka** [comment]
Hi @hemachandiran14 ,
I fixed it in https://github.com/jkaniuka/magician_ros2/commit/761776968aef4bf6c8fd596b3871da49adc87c82. Thanks for reporting this issue :+1:

**Comment by hemachandiran14** [comment]
hi @jkaniuka ,thanks for the response we have installed pyKDL and yet we facing an another problem
![Screenshot from 2024-03-07 12-49-01](https://github.com/jkaniuka/magician_ros2/assets/119487036/3ab573f9-7492-4ac0-8fe5-b0af759b0f3b)

**Comment by jkaniuka** [comment]
Hi @hemachandiran14, 
after adding yourself to `dialout` group please reboot your computer :wink:

**Comment by hemachandiran14** [comment]
I have successfully added to dialout group and have also rebooted. I keep getting the same error "DOBOT magician is not connected"

**Comment by hemachandiran14** [comment]
Just changed the ttyUSB0 to ttyACM0 . worked out finally..!! thanks for all your support :smirk:
